### ISSUE TITLE
Add option to change mac address programmatically.

### ISSUE THREAD

**Issue by kristiKeri** [mmilidoni/zbtprinter#2]
It would be great if the mac address could be assigned programmatically using a method from the plugin.

Thank you.

**Comment by sclearion** [comment]
Indeed. Why would I set it in the JAVA file!!! Why even release it like that. We work in a warehouse with 10+ zebra printers and we can only use this plugin with ONE PRINTER!!!

**Comment by mmilidoni** [comment]
@kristiKeri , @sclearion, thank you for suggestion. You can see [sakurahoshi fork](https://github.com/sakurahoshi/zbtprinter) for that feature.
