### ISSUE TITLE
I am getting socked error

### ISSUE THREAD

**Issue by cetintozkoparan** [mmilidoni/zbtprinter#3]
Hey Michele,
I have a project on Cordova + Ionic + AngularJS. I have also a zebra printer. I am putting printer's MAC address correctly to your java file and I use your code like below to print but, I am getting this alert "Could not connect to device:read failed, socked might closed or timeout, read ret=-1" although I paired my printer with android device. Do you have an idea to solve the proble?

```
cordova.plugins.zbtprinter.print("^XA^FO10,10^AFN,26,13^FDHello, World!^FS^XZ",
   function (success) {
      alert("Print ok");
   }, function (fail) {
      alert(fail);
   }
);
```

**Comment by james12342** [comment]
any update for this issue? i have the same issue, thanks

**Comment by cetintozkoparan** [comment]
Hey james,
You would look at this fork. Hope this helps.. Maybe you need to remove platform folder in your project.
https://github.com/sakurahoshi/zbtprinter/tree/dynamic-mac

**Comment by mmilidoni** [comment]
Hello James,
it is a problem of connection to device. You can try to reboot android device and check if your device is really paired with printer. Check the MAC address of the printer, too.

The sakurahoshi solution is good to set MAC address dinamically.

What is the model of your zebra printer?

**Comment by james12342** [comment]
Hi mmilidoni,
thank you for your reply, i use another android app to connect and can print with the bluetooth printer.
please refer to the attachment.
but no idea why the code i implement above has the error, i did change the mac address by your instruction, any code sample for cordova/ionic for this? thanks
![bluetooth printer](https://cloud.githubusercontent.com/assets/12593813/15585474/4b9ef2ca-2334-11e6-8c76-87f2caa70d6b.JPG)
![android app](https://cloud.githubusercontent.com/assets/12593813/15585488/5f83fc40-2334-11e6-938d-47b44a5339a5.png)

**Comment by james12342** [comment]
Hi sakurahoshi,
i really appreciate your update, will try and see how it works, thanks

**Comment by mmilidoni** [comment]
Hi James,
I am sorry, butr the driver is only compatible with Zebra printers, [iMZ models](https://www.zebra.com/gb/en/products/printers/mobile/mz-series.html).

**Comment by ThayCuongNguyen** [comment]
mmilidoni, 
I have a imz320 printer.. I have a  ionic application that I want to add these printer support.. how do i use this.  I have done the following.
1. cordova plugin add https://github.com/michael79bxl/zbtprinter.git
2. move the file zbtprinter.js to the folder js
3. call this from the ionic controller... 

 try {
        window.cordova.plugins.zbtprinter.find(function(mac) {
            alert(mac);
        }, function(fail) {
            alert('Fail - ' + fail);
        }
        );
    }
    catch (err) {
        alert('errors' + err.message);
    }
4. add  a click button on the ui with the following print command.

```
$scope.printest = function() {


    try {
        window.cordova.plugins.zbtprinter.print("AC:3F:A4:1D:77:12", "! U1 setvar 'device.languages' 'line_print'\r\nTEXT ***Print test***\r\nPRINT\r\n",
            function(success) {
                alert("Print ok");
            }, function(fail) {
                alert(fail);
            }
        );
    }
    catch (err) {
        alert('errors' + err.message);
    }
}
```

**Comment by ThayCuongNguyen** [comment]
mmilidoni, 
I have a imz320 printer.. I have a  ionic application that I want to add these printer support.. how do i use this.  I have done the following.
1. cordova plugin add https://github.com/michael79bxl/zbtprinter.git
2. move the file zbtprinter.js to the folder js
3. call this from the ionic controller... 

 try {
        window.cordova.plugins.zbtprinter.find(function(mac) {
            alert(mac);
        }, function(fail) {
            alert('Fail - ' + fail);
        }
        );
    }
    catch (err) {
        alert('errors' + err.message);
    }
4. add  a click button on the ui with the following print command.

```
$scope.printest = function() {


    try {
        window.cordova.plugins.zbtprinter.print("AC:3F:A4:1D:77:12", "! U1 setvar 'device.languages' 'line_print'\r\nTEXT ***Print test***\r\nPRINT\r\n",
            function(success) {
                alert("Print ok");
            }, function(fail) {
                alert(fail);
            }
        );
    }
    catch (err) {
        alert('errors' + err.message);
    }
}
```
