### ISSUE TITLE
Printing same content printer can't stop connection

### ISSUE THREAD

**Issue by SudarVenkat** [mmilidoni/zbtprinter#5]
Hi i was used zbtprinter plugin. i have same message printed repeated and also printer processing can't stop.

**Comment by mmilidoni** [comment]
Hello SudarVenkat,
what is the javascript code that you run? 
what is the message printed?
is the printer enabled to receive ZPL commands?

**Comment by SudarVenkat** [comment]
Hi Milidoni

my javascript code.

cordova.plugins.zbtprinter.print("My printer Mac address", "! U1 setvar "device.languages" "line_print"\r\nTEXT ***Print test***\r\nPRINT\r\n",
    function(success) { 
        alert("Print ok"); 
    }, function(fail) { 
        alert(fail); 
    }
);

my message 

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAgAElEQVR4Xu2dBdQsSZGFcYfBfZiHu/swwGNwW2Bxf8ji7s7gbou7u7vDw10H1ze47eBue7+hc092bpZ3Ff8f78Y5cbq7OivlRtatyMjMqsMfzmIEjIAR2CYIHH6b1NPVNAJGwAgczoTlTmAEjMC2QcCEtW1M5YoaASNgwnIfMAJGYNsgYMLaNqZyRY2AETBhuQ8YASOwbRAwYW0bU7miRsAImLDcB4yAEdg2CJiwto2pXFEjYARMWO4DRsAIbBsETFjbxlSuqBEwAiYs9wEjYAS2DQImrG1jKlfUCBgBE5b7gBEwAtsGgbGExXmnlJ5NegLpSxpafGQd3yW9gfSc0p9I3yH9b+l3eqJ0pNX5N17lcYg+Xy19qvTXRR6Ud33pdaTnkf5R+m7pE6Rf7lke7bmF9CrSM0m/L32j9InSX1TyuISO3U56EenvVu2jvG83lHeMVb5n1+dHpN8q0v2Xfj+rR12PW2l/j9OcZAQCZ6n0n5+vjr1dny+U/rSS73N17KbF8T/oN33/fdLnSA8eWB/6J/Xhenq29M8N5x+o4zeX0i+PKf2Y9GlS6lvKmXXgDtLLSulXn5a+SPpy6d8H1m/W5GMI6zGq0dWkp13V7C36vHKllkdYAYrBXiX9qPTE0ttKMdoB0j6k9Vilu6sUkgJ0yiUPDH4lKaSEQGx0AIjtNdKPS48tvY30KNKLS79QqWd+6ET68S7pWaXPlH5TeoZVeZ/R56Wkv8pOuPqqLIjnTdLjrMoHV4iM85OcX18eujoOsSIXlX64qNO59Ju0TXJP/XFEKZ3sTy3p/NfmEEiE9TplyQ0XOar0jNIbSunP9AX6Zy6JsOivqZ/SF08t5aZ4dOllpB/qUVXKgVTOl6Wlf3OTLOWWOvCMVX3eqs+/SK8tPa90lxSCTUJ+75H+Vsr185tVnS6nz4dL79ujboslGUNY11PtYGwET6CJsGgwbP4Q6QOl/1yds78+ucAfL4WI2uQC+vMT0kdJ753lgQcF+99aimGQq0pfv0r3yCzTc+v7Z6UQ3rU6yqOce0i5O70/S0vngsBuL33K6jidBULCc8MbSx2HTkx5eGVglYTjF1v9gKjogDXCaqsiBP3mSv06muW/JyKQCIubxaOLvPbTb/oWI44LSb+X/Z8Iq+YN471/UspNlH7QJTuV4PSrRDgBlFUjLOpDv4SouE6SB0YduIkfX3oaaeqvkCV9E+JKdeeGyPV1zVXa73ZVbqn/xxBWXjdIqImwHqb/7iPFMF8vGoRnxXAOMmmTB+vP+1dAw5uCKBhi4jkhuMe4wCeR/qzIFK9ppxSi/WtDgXiEP5IyRMP7ywVj/1L6Cul1V39cXp9vk2JUPLpcIDXuqnhstWFkGvYNISzaRQfHVQcTy3IItBEWtcAr/pyU0cDds2q1ERbJXirlpgaJ0L/6Cn2AG16NsBhhvEBK/0zeYMr3XvryCCkePMO+k0t/KH26lJFILnhk9HduxowetoTMSVhc5LjNjPX/UbT2U/rN8AlmbxO8FFzmY0nLsfQrdQyP6WhS7iIQCQTxZGny5lLepGUY20ZY1PVWUu4yeGq54MZTRk5Yd9ZvvERiZXTWXCArSIu7IB5iKWMIi5gdHtqFpbVhQKUYH9oQAl2ERTHvlHIDPoU03RS7CAuioM813diaqt9GWNxsGfrh9XEDrvXLRFjc+ImJMVxlKJhL8uZrN+QNwTo8mzkJq6k23E0IZD9fSrC6TYh7AWiN2AjcM0TrMjZBbrymz0uvMByiw86gA3BHYrhIDA95kPQBUtzr0mVOQ1bIlqB/KUMJK10wkO4bRrbBp41HoA9hEZ8k3kN8as+qqDbCIn6Fx/x7KTeh8ibbVts2wmo772X6EyJi2Njl0SVvjGvvG+Oh2+yZSxHWSVVtxsV83k1KHIuhXDJsU6sgCbwrhpWlPEkHCEKSZ22GJqW/k74wa4ehGNcPFYaK3K0uKWVmD7JF0pA376Ap7+ROQ5C1WZmhhEUwlGEHHtvfhjbA6Scj0Iew6NfczJi9++KqxERY9F+C2giePF4YQzDivAzdal54W6XHEFaKHdNv71fJnNHHPlJu8MSOGSFwjXFj3jKyFGERs+LCRohdXVrKsBDBLT1ZgQh3nUOlUwmLOxeziQwJbyLlLtZWXs0weHF4c5AMxJFkKcIimAtJEvgnTmdZHoE+hMUEEjEshoV480htWUOqPQSGB04gPAkxJW7sSQiDlMM6/htKWMzOM4lEaIYhY7kciDzTTTaVTV9nUmtL3SCXIizWgjCVD3AEC5mFu6J0tzQF/jI7HTazyHBrCmHtWBmJoDcdI7nAbeXldeA75xGbYIYQ4+Vu+1KEtUvlMnyueXJlff17HgT6EFabh0VfZ+kDwjVHGIFZb+K4LJVJHhn9nfBDEsiMm24pQwiLoSc37J1SJnmalvZwXbCEh5jwOaQMCQln3EjatNarUrV5Dy1FWHkrAITYFJ4OdyOIjKFOLj/WD2YW22JYaUhYi2EdT+cy/NtXynqofHEm5TeVl9cBo+2WEme4hrQMdLfFsNLdahMxLGZodqw60by9wbk3IdCHsIbGsFhHB3m8VppmnumX9M8kBMNrw8W+hEU4g0kohp9DZ/tSHJa+Tx23hPw7CIuGp8WgjOVrLm8Cp22WEK9jl5Q7SL6AkhgBK+9ZtcvdC8IZKgzD3itlaEqcoVwmQX5ts4Ssk2E4wN0xd/lTPfrGsIjfMXRgSHrHoY1w+o0h0Iew6C/EOIfMEn5Q6dNukTmC7kwSsbaQmUhGCUNkhxIzmdQU8xqS18bSzklYrKZl6EfAkQs/l7ROqStgztCQAGE5E0e9uTsxFs8X3XH8cVLIZGyQHTedxZkYjEB7uXUmtYOAOl5cbdqX4CtDBIbALOsopS9h4eXRTsevKiAueKiLsFh0SUx26DosZu3wrsqbblfT+nhYycvH82tat0e9mXVmoXVaEJ3KZnjIKCeFZ7rqtMj/cxJWGtOzj5AFcklYAMlYnWHfBaVtdxZcZLY7sNiNKeOUNq0RYVkE65OSMGvIUHHsBc7w9AVSYg54Z9SzSSA2yIz4A+52IuUd+o5XR5CTTlOTvoSVtv40DS1bque/NohAG2GxVYxZZG6+9Oc0i0zxXeuwXqw0XB/M0KUYV59qdxEWM4J4fFx3eFdNgXPWSu6RsjKe0Eke9kjeGdvuWBy+JWROwmK9FQFrWJwtPHgKHGO4xKwgM4XlProaKCxJYGkCizbZ0kPwmZk7xvZMCSeQyY8V7V+SsqCzJl9ZndcEPoF+YlOsXGcVe02YdTxk9QfeFfsk2d7A8JWOt0vK1PBO6dca8uhLWKnTMGzou3m7qW0+Ph6BRFgQU1qmgo2xC0FpZrSJ9ZTxpi7CSnHYU+ncnOi6atpGWMRtucmzfpH+U1tkzARUWs/H7PnzpGzCJpQCceIo8BAB+jafW2amcE7CAnSC31ycLHhkQzGxIEiMFb4QSx8hOE+nSE9rYCU6hEIwMV/8lqaV2/LES2NDZ5MwFMR7axM8L+5eSRj24ukxXYyXxXYISLZtsV1fwoJ4Gd52xfr64Og04xFIhJXnwAiBixwC40KvbcHqIiyGgwwLiU8Sp+wrXSvduzZTc9Ml3JGENZFsa9spZbsPe2HZS0g5W2aGkMpOJay+ADudETACRmAyAiasyRA6AyNgBJZCwIS1FNIuxwgYgckImLAmQ+gMjIARWAoBE9ZSSLscI2AEJiNgwpoMoTMwAkZgKQRMWEsh7XKMgBGYjIAJazKEzsAIGIGlEDBhLYW0yzECRmAyAiasyRA6AyNgBJZCwIS1FNIuxwgYgckImLAmQ+gMjIARWAoBE9ZSSLscI2AEJiNgwpoMoTMwAkZgKQRMWEsh7XKMgBGYjIAJazKEzsAIGIGlEDBhLYW0yzECRmAyAiasyRA6AyNgBJZCwIS1FNIuxwgYgckImLAmQ+gMjIARWAoBE9ZSSLscI2AEJiNgwpoMoTMwAkZgKQRMWEsh7XKMgBGYjIAJazKEzsAIGIGlEDBhLYW0yzECRmAyAiasyRA6AyNgBJZCwIS1FNIuxwgYgckImLAmQ+gMjIARWAoBE9ZSSLscI2AEJiNgwpoMoTMwAkZgKQRMWEsh7XKMgBGYjIAJazKEzsAIGIGlEDBhLYW0yzECRmAyAiasyRA6AyNgBJZCwIS1FNIuxwgYgckImLAmQ+gMjIARWAoBE9ZSSLscI2AEJiNgwpoMoTMwAkZgKQRMWEsh7XKMgBGYjIAJazKEzsAIGIGlEDBhLYW0yzECRmAyAiasyRA6AyNgBJZCwIS1FNIuxwgYgckImLAmQ+gMjIARWAoBE9ZSSLscI2AEJiNgwpoMoTMwAkZgKQRMWEsh7XKMgBGYjIAJazKEzsAIGIGlEDBhLYW0yzECRmAyAiasyRAOzuCfxRnn0+/PNORyFx1/XPHfI/X73qtjz9XnTbP/76TvT+qo0df0/xmzNFfQ97dnv1+k7zfMft9e35+S/T6Xvn+uKONI+v33wUgMP+EUOuXa0ktIzyw9ofRHq/q8V5+vl/6yR7b7K83VpBeXnkb6W+k3pOTxcun3e+ThJP8GBExYy4Pel7DOoap9WnrkrIof0vfLSv+4Ora3EBb99MbSp0qP0WKyPfoPAn9/QxrOfbz0li15/EH/3Vb6guW7hkvsQsCE1YXQ5v/vQ1hHV7Hvll4kKx7P4cLSr2fH9hbCupna/JyepoBwdko/VaSnrz9/RXx9srqBEr20T0KnWQ4BE9ZyWKeS+hDWfZX4oUXVrqvfryiO7Q2EtUNt/qr0aFnbIfNnSH8mxRMFq+Nl/79P3y9ZYHVl/X5TceyB+s0w8JjSm0uvmf3/a30/w6qM5XuJS6wiYMJavmN0Edb5VaVPFtV6un4zTCnP3RsIi3jdwzM8PqHvO6V/yo5dTt/zOBx/EZv6bpbmjfr+H9lv8iUemOSoqzyIjyW5tb5AjJYtgoAJa3lDtBHWsVSd3dLzZtUiwM1FxB2/lL2BsN6jRufeEjEqhna5HFE/GDIfOztIQP2Dq9/geqg0jweeWr/3FPkwDHxxduyV+n6d5buIS2xCwIS1fN9oIyyGNgwHk+BFMKNVzsql//cGwnqJGrtPhslD9L30QPn7O1JIKMml9IXhHsKw8QvZf5A/Q8jSFqV3+2OlOfnyXcQlNiFgwlq+bzQR1gGqCrOAuTCb9ayWKu4NhNXHQvsp0Z4iIUs3WKqAlNgSEztLJWPOYdlHLkfRj7/2qYTTzI+ACWt+jMsSSsJiJuqn0itK8/VRHL+R9B8mrE4jEeNKa9NI/BHpRaUJ60vr+7uyXA7Wd7yuUk6nA98sDuLd/aazBk6wCAImrEVgXiukJKymGuzQH4d0VM8e1r+IKcWqElzEvJgpTHIZfXnnSMI6rs6rxQ+X7zku8XAmrOU7QV/CIpaVz47VarodCYtV8efsgP3L+j+fBWxKflr9sVt6yizBg/T9oOIEE9by/XyWEk1Ys8DammlfwiJuciHpZ1ty246ERbCbGbs2qc3glekJhr9Feu7sj5fp+y5pGXMyYS3fz2cp0YQ1C6yDCCvtJTyBzmJ1dj7T9XH9PlCatuKUGe+thHUSAcG6qgtmgBCjuoaUfYGlOIa1fD+fpUQT1iywjiIsTrqK9A3F2ffR70c05Mh2FbatJNkOm5+nelgQO5uciV0lIcgOdv/TgFMZ5xoyS8iC0r8s301cYg0BE9by/aJtHRb2YN3R9bJqMbzBk6itxXqsjt81S8tWkwe3NOkI+o/hWL6uiSl/LvgkW/lpDZDda6R4nUl40sWVpD9paTcxs89n/zetw8LbzfcgMnt70uW7iEtsQsCEtXzf6Nqas++KnPAkknxMX5j5KoeGd9Cx/HEyu1cXc1OcrFxASf4Erll0mWSrEtZxVEFWnrMNJ8lXVr+7HgfDCvhyaUItTsaNIt/wDDnm+wuX7y0ucQ0BE9byHaKLsKhR7ekE99LxRxXVJeBcBuV5DAukUwoX7QulPAcqCY+vYXV3LluRsNhaA5HkewG/vSKrb/U0IRuf2QCd5J768ujsN9t2COIToE9SPgusZ1FONhcCJqy5kG3Otw9hMfX/1uLiqQ0NsR9PcLhWUdyr9Js4zw+kPAPq9NI7S/GmcoG8ypjZGMJi72PbAlfKZMjWNmxrQoxH7UC0pacDMX+xw3xsx0l4Q3YE6nNJT2ugjJtI86E4j6lhISnbcyxbBAET1vKG6ENY1OqsUuJW+YZdYk3skcvXKPEUTjwDngQ6RHhSAQH9sj5jCKtPuWOffMB5T+tTQCVN/iRU4ncQHxuc+wiPm2EW1rKFEDBhLW+MvoRFzRi25I9AScfyoQzHmOZnkWn+uOSmljGTdvfVxVvzirYaYd1RdX3iSDOVj25maPkEKWTUJHiyeKOQZN81cyOr59OGImDCGorY9PRDCIvh3AekzF4l4YK6gDSf9Ur/saGXGTMWnPKdGS6GNgwNiVexufpt0ratJpEJK+HEk1zTM90JvuOx8iRXnu7AEDufhJhuceewMQRMWBuD0hkZASMwNwImrLkRdv5GwAhsDAET1sagdEZGwAjMjYAJa26Enb8RMAIbQ8CEtTEonZERMAJzI2DCmhth528EjMDGEDBhbQxKZ2QEjMDcCJiw5kbY+RsBI7AxBExYG4PSGRkBIzA3AiasuRF2/kbACGwMARPWxqB0RkbACMyNgAlrboSdvxEwAhtDwIS1MSidkREwAnMjYMKaG2HnbwSMwMYQMGFtDEpnZASMwNwImLDmRtj5GwEjsDEETFgbg9IZGQEjMDcCJqy5EXb+RsAIbAwBE9bGoHRGRsAIzI2ACWsd4TfrJ89Ez4U3C+fPVJ/bJs7fCBiBBgRMWCYsXxxGYNsgYML69xAW7xK8vJTXz59Jup/0Z9I90g9LeXvLx6Wbes3UUVd58raYUk6lA12veuec40mvIL3wyuOkDbxN+kfSQ6R4oh+Vvl/6xw1dATuUDy9LpZxcDtaPc3SUcQv9/8wJ9ai9ZLaWHW/d4W3RB0p5YS115lVq35N+bIXHbn3+fUJdfOoKARPWeleYe0h4NBV3FymvnS8vwrJT8kbme0u/toHeehvl8dSGfLoIi7ci31Z6P+k+PeryQ6XhBa0vk/6tR/qmJPRNXk9/3UqCPoT1AJ33oAnldxEW9sOOvOMxf9ltrUhInHdMfmpCfXyqEDBhrXeDOQnr+Crq+VJemd5Xfq6EV5fyPsGxgvfGK9ubyKaNsE6g814pxRMcKs/TCRDln4eeuEpfe7V8yqoPYT1diW81smxOayOsE+l/yPTSA/Ln/ZDXlvKWbstIBExY68DNRVjcgfE4rjHCTrz09IJSXvQ5VLAvL0Ztez17E2Hx1mQurssOLTRL/xB9x9MZKpDrJ6VnaDixD2HVbDmkHk2EdURlwstWx9iSF7byElzqbxmBgAlrHbS5CIs7PXf8mjxLBz8nJUbEHficlUS7dYy7+dAh1hV1TtcdvYmwbqhzIbuafFAH3y09VLrvqt7EckrhLdW8gfpbA/vmQ5X+vi3n9CGsL6/KzrPB6/tVz7q8XOl4W3Yp19MBvKtS8KCeI/2K9LjSa0rPW0n3ER27uNQxrZ6GyJOZsNZBm4OwiHXQiU9Z2IeLGULhwk9CvOgp0ptWbHkpHSMY31fwUj4hPWPHCU2ERVkEkku5sQ68RPqP7A8uUIiXi7QUhoVNZF2r2rl0EAJvky7CwjuEQMrY0kl0jMmNscL1wsTChYoMfqrfBN6ZIEjSZsudSvSBsZXYm88zYa1bfw7CYl0X+ZZCQP2RleN4WnT8kuDwdiCLvkLAuc9wrEZYx9K5v60UBFHhedVkhw5+t/LHs3WMGbs+AtG8U1ojyvz8LsI6sRJDIrnQHog1J9o+dcrTnFs/Pls5CQ+6NiN5Qh3/hhSb5sIEyO2GFu70DrqXfWAIYRGQ5sI5WaUjQSxpOPUIfWc2qRQIiRm1mtSGREyVn1TaZ1jIlD/DmdzD+JJ+n61SWI2w8M6YGSwF72J3y4XD0O+0xf9g2neiAc/yudn5xHxYMlF6iV2ExTCUIWEuLBNhScYU2aWTmTgphYkNljHUBCIrCZt4JMtZLAMRsIe1DtgQwjpIpz6wgjd5ELBNMYpX63sZoP28jnG3bhJmBl9T+ZNO3hV8x0t5q5QhShKGnW+TPqGSZ9eyhiFdCg9rR3HCq/Sb2FyXnFwJwIUZuCR4iGeXlkPNLsK6mM4ph1xt3mFX3dL/4HenIvGP9Zu6N8mt9cfTKn9yo/tJ34Kd7l8ImLDWe0JfwsKLwGNhXVUuDDsItH4zO8iShAOKdG/U76u2dELS15YycCF2LXHYpTS5F0CsjK1FnPvkSpmbIiyC7zUvg3VnNaIsq8LQ8ebZQeJ+xIrwuIYSVo3wH6Z8WEuGQDAM11hy8Utp37gWSzyuVVScNVZtQ9ir6H/W1JWCt1t6gZVkPpQjYMJa7w99CYvZoJtVutLtdYygeS7v049LFMeYubtyS1eE9GozVATp8ZSahLs2AWuCy0kO0hfiWcRM5iIsvLpnVDCBDPCQmoa+qY5MKOSTDxy/nJR4Fh7aUMKqLZTFM2KJCDiUs3d4dnjC2LWNvN6l/8u1V11DXtJzXimQMZMilgEImLDWwepDWHQ0tlyUwp2Wi+wvxR+1C45YD9s4mqSJsBhakV+TQBq3zP5MXgqe3yYIizVI+VCTGBneCvXaWakUXiTeZJscU38y1Z8v52D5QbohjCEs1n8lbyqVDQZduwuIE15fClHWhLVh5y/+wHsiBNAkLLp9T+VPvDL6jGUAAiasdbC6COsISv52aX7RkkMaduXT2innB+vL/Ss2gbCa1ic1EdZ1dA7DkprgxeHN5ZK8FI5tgrCYqme5QJewQh/ifH1XQv3PhAQTE0k4l/he8srGEFaTB9yjOofZslxuks7D6y29s7GENXSZSp+6h09jwlo3cRdh4THULkL2zuUXXZ5r0xaTJylRGcBN591NXx5T6X1NhHUMpcVLYQ1TktxL4dhShMXQ7kbSPgFlJhEYwuaxQGYK8xjcGMLCQypvKkMuZiYP8KTwuHIxYQ1BcYa0Jqz+hIV3QcyBmEzZiVm53OR5HEf/4Unls1/pfALBLLjkiQcMjZiOZwp8V4OtmwjrHkr/qOwcvBTIi3yTLEVYlNdn4zbeKunyWB5kxxMh8qUbYwirtrxij/K9q5RJC1a7MzxkuMaEAE+eKIXZPYbYuZiwGjrmUodNWOtI1zysbysJO+254/JZyv46UItp5emaPKahdq4RFmuUCBq3eSmUsyRhUR4B9/+U7m5oJG1h+0uSpmH1UMLiUTqs3yqFoVxt0SeP3OGRPqVATmW8yoQ1tMduOL0Jax3QGmG1Qc5KdVasdwkX0ZukfYcpDEVYmFpKSVh4Ka+V5kskal4K+WyCsMr6MDuI54iH+XBpuZ+QdrCkYk9xIksKGArmq/lZ00a8r5ShhEWfZkV7LjxXrG0PYW25AufTtl9kGZmwKgZa8pAJax3toYTFlHVtBqhmw7b9dnl6hp0MFSG4UspZQtYE5UH4tuD/HISV148nK0BCxNNyeaJ+3Lly7I7ZsXw2s2zzUMIac/2UK+xTHjxZIX+GFd/Lx2WPDbp7lnCEpUxY0wiLDox30fcJm3hEPK7lJlJiN/kwbo9+s42DdVzEn2oLRFmEmIgML4WnfLLwc1NC/IhZ0LHCOq9yjxzLCfBU0nOxGEIzQbBJYctSuXdwSP61dWCcX87kcXMqnw3WtQ4Lr7q2TIJtQmwXsgxAwIS1DtZQD4uzCeQ+fgDmKSlBdjbpEvzlov6BFA8JaZpZhBx5tAvStCBxRFX+75SphNXkqeRbiljiURv6Tan3VMKqbeWhPtxU8sfz1Ly93UpTLgzO2+KV7lMsW5xrwloHpG1ZA/EW1lmVO++ZHTyPtGuP3xCzsUyCYWEpzCJ+dXWQ4cqmV0onwmKbDRt6S2HI9/uWhpSB9JQUfNIjY5qGpkPwKdPmhMXG73JGlhtBIvpaObWtPKTLbxD8ZnibD2U5xl5CZhmbnr/f9Cw0FtxyrmUAAiasdbC61mE1bWRlmMZq5ymPLkk1IZDNxV0+WYHOzfAvTfkzO7iJ573nCCTCaiKeMqZTdjUuZi7qUk6nA8y2Ik0PwBvQbf9f0pywIHoIPxc8WB5R3fSki6ZZ3PwGQX4M5VnfVsoOHeCpEjWpPaq5a6fDFCxCn2vCWjdvF2Ex27dbWj7ALV2I+TT92I7TNKxix3/+yBeGkhBLX2HYUnuhA0s1WIKAsFWEi2nn6nuZN3sSD2ooEKIFm/LNPHig7G383eo8VviTf19hxXy5upxV8NQlCbin/Gv7CEnXtHcPm/LM+/IRNuUNgjzwFIkbllJbs0UavHE879LjY30X51gGImDCWgesi7BIfVFpbXjBRcSF1Rb8Zb/cHimbcEvBFgxNXiwtnwJB2nxYNdDMhyUfMkvIYlcu2HLGj6EVpMdSilzYU3iQtPRsSDP1sS5DZwnBmHVppbDWimfb554QmPM0icdW0j9Ox/C8ciE9w/ByfVbtiaNHUTpim7XninlbTgXwPodMWOso9SEszmh6IwvHucM3CUNHguXMxHFXZ/sKs2fciXlPYdNbWIY8tbOp7CGERR5sDSov2JQ3T4zgCQQMtRiO8byvpud7lXGgPv0yTzOUsJiJ5Xlg7KMshRsF2354CigbucGcYXBNzqyDtSE3pMdNpRSwSM90x/vl5lN7DyRruZgh7PMgxqFYhU9vwlo3cV/CImBKAL62uJNp73ITMqWANV5Y7QmlbR2NVfRcWDWvbEgHHUpYLJugbOJPY6W2BmtoXkMJi/zZPsWyEJ6cOkYYJj+64USIjkfRtD2hoalMPFTIqjasHFPPve4cE9a6yfsSFmc1vVkYz4kH8KWYSiqh9pzxrg6HJ8ND7TYxmzSUsKgbZMXjYQg+DzI6Mv0AAAciSURBVBWeW86C0bRUY+j5Kf0YwuJcbPA6aW0PZ1tdWAvHc83a6k1Mjte2dT17Pi+H7UJsCofsLCMRMGGtAzeEsAjW8maZmtvPs5jKZQkMMRgOlHGhmunwxNjMzMbosS8iLfMdQ1jkwQp9hoaQT5+6s2qdV3RBdE1T/UO661jCogyWZ2CHphdn5PUgDsVztBjW95ntZdjHtiywKd/OU7YPT5U3RG96wewQHEOkNWGtm3EIYXFm06pt7s4E4A8uegnDrJ1SZqxYL8SMGZ4XHtT3pSxnIDgMEU4dApYddCxhpXzwVBiaMqRhewprjyAwngjB41gIRjMMQzcZn5lCWKnubBsipsXNBW8RIkuLdQnQU+d3SHnP4lBh/yS7F5iFpRzWr7FvkeA+mBAeQDeJydA6hklvwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAImLDCmNINMQLxETBhxbexW2gEwiBgwgpjSjfECMRHwIQV38ZuoREIg4AJK4wp3RAjEB8BE1Z8G7uFRiAMAiasMKZ0Q4xAfARMWPFt7BYagTAI/C8pneSHkK+hKgAAAABJRU5ErkJggg==

![download](https://cloud.githubusercontent.com/assets/5656417/22967276/df5e6c2a-f38b-11e6-9938-4261bdb9dc1e.png)


my printer name is epson tm-20 (portable bluetooth printer)

**Comment by mmilidoni** [comment]
There are some errors on your javascript code about inverted commas, fix 'em first. 

I am not sure that project (zbtprinter) is compatible with other printer besides Zebra iMZ series. 
Please, inform me if you successful manage to print on epson printer. Thank you!

**Comment by SudarVenkat** [comment]
ok

**Comment by SudarVenkat** [comment]
I was used 

https://github.com/srehanuddin/Cordova-Plugin-Bluetooth-Printer

plugin to print text on all printers but base64 image was not printed correctly on my printer.

**Comment by mmilidoni** [comment]
Ok, thank you. I close this issue.

OT: you could print images with that plugin using printImage method.
